#!/usr/bin/env python3
"""Host tests for the Tilelink firmware (no board or chip needed).

Compiles the real NFC/tilelink.c and the APP_TILELINK command loop from
NFC/nfc_app.c with a PC C compiler, with the TRF79xxA / UART / MCU calls
stubbed (see harness.c), then checks:

  * the exact bytes the firmware hands the TRF79xxA FIFO, against the frames
    tools/tsi_host.py builds (whose CRC is checked against the wiki examples),
  * every UART reply line, field/modulation handling, re-setup after errors,
  * that malformed commands are rejected without transmitting anything,
  * that tools/tsi_host.py's limits and status names still match the firmware.

Tunables (TILELINK_MAX_BODY, gaps, timeouts, NFC_FIFO_SIZE, line size) are read
from the firmware sources each run, so changing them doesn't break the tests.

Usage:
    python tests/host/run_tests.py          # from the repo root
    python tests/host/run_tests.py -v       # also print the driver-call log of every test
    make test                               # from TRF7970ABP_RFID_Reader_Demo

Needs a host gcc: $CC, gcc on PATH, or MSYS2's C:/msys64/mingw64/bin/gcc.exe.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FW = ROOT / "TRF7970ABP_RFID_Reader_Demo"
BUILD = HERE / "build"

sys.path.insert(0, str(ROOT / "tools"))
import tsi_host as tool  # noqa: E402


# ---- Pull the code under test and constants out of the firmware -------------

def extract_app_block(source: str) -> str:
    """The '#ifdef APP_TILELINK' ... matching '#endif' block of nfc_app.c."""
    lines = source.splitlines()
    start = next((i for i, l in enumerate(lines) if re.match(r"\s*#\s*ifdef\s+APP_TILELINK\b", l)), None)
    if start is None:
        sys.exit("could not find '#ifdef APP_TILELINK' in NFC/nfc_app.c")
    depth = 0
    for i in range(start, len(lines)):
        if re.match(r"\s*#\s*if", lines[i]):
            depth += 1
        elif re.match(r"\s*#\s*endif", lines[i]):
            depth -= 1
            if depth == 0:
                return "\n".join(lines[start:i + 1]) + "\n"
    sys.exit("unterminated '#ifdef APP_TILELINK' block in NFC/nfc_app.c")


def define(source: str, name: str, path: str) -> str:
    m = re.search(rf"^\s*#define\s+{name}\s+(\S+)", source, re.M)
    if not m:
        sys.exit(f"could not find #define {name} in {path}")
    return m.group(1)


def generate():
    BUILD.mkdir(exist_ok=True)
    trf_h = (FW / "Hardware" / "trf79xxa.h").read_text()
    app_c = (FW / "NFC" / "nfc_app.c").read_text()
    tl_h = (FW / "NFC" / "tilelink.h").read_text()

    enum = re.search(r"typedef enum\s*\{[^}]*\}\s*tTrfStatus;", trf_h)
    if not enum:
        sys.exit("could not find tTrfStatus in Hardware/trf79xxa.h")
    status_names = re.findall(r"\b([A-Z][A-Z0-9_]+)\b", enum.group(0).split("{")[1].split("}")[0])

    regs = {n: define(trf_h, n, "trf79xxa.h") for n in
            ("NFC_FIFO_SIZE", "TRF79XXA_RX_NO_RESPONSE_WAIT_TIME", "TRF79XXA_MODULATOR_CONTROL")}
    (BUILD / "fw_constants.h").write_text(
        "/* Generated by run_tests.py from Hardware/trf79xxa.h - do not edit */\n"
        + enum.group(0) + "\n" + "".join(f"#define {n} {v}\n" for n, v in regs.items()))

    block = extract_app_block(app_c)
    (BUILD / "app_tilelink_block.c").write_text("/* Generated by run_tests.py from NFC/nfc_app.c */\n" + block)

    consts = {m.group(1): int(m.group(2), 0) for m in
              re.finditer(r"^\s*#define\s+TILELINK_(\w+)\s+(0x[0-9A-Fa-f]+|\d+)", tl_h + "\n" + block, re.M)}
    consts["NFC_FIFO_SIZE"] = int(regs["NFC_FIFO_SIZE"], 0)
    consts["REG_NO_RESP"] = int(regs["TRF79XXA_RX_NO_RESPONSE_WAIT_TIME"], 0)
    consts["REG_MOD"] = int(regs["TRF79XXA_MODULATOR_CONTROL"], 0)
    return consts, status_names


def find_cc() -> str:
    for cc in (os.environ.get("CC"), shutil.which("gcc"),
               r"C:\msys64\mingw64\bin\gcc.exe", r"C:\msys64\ucrt64\bin\gcc.exe"):
        if cc and Path(cc).exists() or (cc and shutil.which(cc)):
            return cc
    sys.exit("no host C compiler found: set CC, put gcc on PATH, or install MSYS2 mingw64 gcc")


def build(cc: str) -> Path:
    exe = BUILD / ("harness.exe" if os.name == "nt" else "harness")
    env = dict(os.environ)
    env["PATH"] = str(Path(cc).parent) + os.pathsep + env.get("PATH", "")  # MinGW needs its DLLs on PATH
    result = subprocess.run(
        [cc, "-std=gnu99", "-Wall", "-Wextra", "-Wno-sign-compare", "-Wno-pointer-sign",
         "-I", str(HERE / "stub"), "-I", str(BUILD), "-I", str(FW / "NFC"),
         str(HERE / "harness.c"), str(FW / "NFC" / "tilelink.c"), "-o", str(exe)],
        capture_output=True, text=True, env=env)
    if result.returncode:
        sys.exit("harness build failed:\n" + result.stderr)
    if result.stderr.strip():
        print("compiler warnings:\n" + result.stderr)
    return exe


# ---- Test cases ---------------------------------------------------------------

class Case:
    def __init__(self, cmd, out, raws=None, status="NO_RESPONSE_RECEIVED_15693", rx="-", has=(), lacks=()):
        self.cmd, self.out, self.raws, self.status, self.rx = cmd, out, raws, status, rx
        self.has, self.lacks = has, lacks   # has: exact log lines; lacks: log line prefixes


def make_cases(c, status_names):
    hdr = c["HEADER_SIZE"]
    body_max = c["MAX_BODY"]
    line_size = c["LINE_SIZE"]
    err = lambda name: f"ERR {status_names.index(name):02X}\\r\\n"  # noqa: E731
    ok, bad = "OK\\r\\n", "ERR ARG\\r\\n"

    def fifo(frame: bytes) -> str:
        n = len(frame)
        return (bytes([0x8F, 0x91, 0x3D, (n & 0xF0) >> 4, (n << 4) & 0xFF]) + frame).hex().upper()

    def writes(addr, data):
        return [fifo(tool.build_frame(tool.CMD_WRITE, addr + i, len(data[i:i + body_max]), data[i:i + body_max]))
                for i in range(0, len(data), body_max)]

    setup = f"SETUP {c['ISO_CONTROL']:02X}"
    reg_noresp_w = f"REG {c['REG_NO_RESP']:02X}={c['NO_RESP_WRITE']:02X}"
    reg_noresp_r = f"REG {c['REG_NO_RESP']:02X}={c['NO_RESP_READ']:02X}"
    reg_mod = f"REG {c['REG_MOD']:02X}="
    wait_w = f"WAIT 10 {c['RX_TIMEOUT_WRITE']}"
    wait_r = f"WAIT 10 {c['RX_TIMEOUT_READ']}"
    gap = f"DELAY {c['GAP_MS']}"

    ex = tool.EXAMPLE_BODY
    multi = ex + bytes.fromhex("1122334455")
    line_data = bytes(range(tool.LINE_MAX_DATA))
    raw_max = min((line_size - 2) // 2, c["NFC_FIFO_SIZE"] - 5)
    raw = bytes(range(raw_max))
    fail_data = bytes(range(1, body_max + 3))

    return [
        # Happy paths. The first packet also turns the field on automatically.
        Case("T", ok, writes(0x80000000, ex), has=[setup, reg_noresp_w, wait_w]),
        Case("W 80000000 " + multi.hex(" "), ok, writes(0x80000000, multi),
             has=[gap] if len(multi) > body_max else [], lacks=["SETUP"]),
        Case("w 0x1234 aB", ok, writes(0x1234, b"\xab"), status="NO_RESPONSE_RECEIVED"),
        Case(f"W 80001000 {line_data.hex()}", ok, writes(0x80001000, line_data)),   # longest line tsi_host sends
        Case("R 80000000 8", "DATA C0FFEE\\r\\n", [fifo(tool.build_frame(tool.CMD_READ, 0x80000000, 8))],
             status="RX_COMPLETE", rx="C0FFEE", has=[reg_noresp_r, wait_r]),
        Case("R 80000000 FF", err("NO_RESPONSE_RECEIVED_15693"),
             [fifo(tool.build_frame(tool.CMD_READ, 0x80000000, 255))]),
        Case("X 01 0000008000000000 0800000000000000 0807060504030201", ok, writes(0x80000000, ex), has=[wait_r]),
        Case(f"X {raw.hex()}", ok, [fifo(raw)]),
        Case("W 80000000 01", "DATA AA\\r\\n", writes(0x80000000, b"\x01"), status="RX_COMPLETE", rx="AA"),
        # Driver errors: reported, TRF re-set up, multi-packet writes stop at the first failure.
        Case("W 80000000 0102", err("PROTOCOL_ERROR"), writes(0x80000000, b"\x01\x02"),
             status="PROTOCOL_ERROR", has=[setup]),
        Case(f"W 80000000 {fail_data.hex()}", err("PROTOCOL_ERROR"), writes(0x80000000, fail_data)[:1],
             status="PROTOCOL_ERROR"),
        Case("W 80000000 0102", err("COLLISION_ERROR"), writes(0x80000000, b"\x01\x02"),
             status="COLLISION_ERROR", has=[setup]),
        # Modulation and field (field is on here from the packets above).
        Case("M 10", ok, [], has=[reg_mod + "00"]),
        Case("M 100", ok, [], has=[reg_mod + "01"]),
        Case("M 10", ok, []),
        Case("F 0", ok, [], has=["RFOFF"]),
        Case("M 100", ok, [], lacks=[reg_mod]),          # field off: only remembered
        Case("M 10", ok, [], lacks=[reg_mod]),
        Case("F 1", ok, [], has=[setup, reg_mod + "00"]),  # field on re-applies 10% ASK
        Case("M 100", ok, [], has=[reg_mod + "01"]),
    ] + [
        # Malformed commands: ERR ARG and nothing transmitted.
        Case(cmd, bad, []) for cmd in [
            "W 80000000 123", "W", "W 80000000", "W 123456789 00", "W zz 00",
            "R 80000000 100", "R 80000000 0", "R 80000000", "R zz 8",
            "M 50", "M 1000", "M", "X", "X 0G", "Q", "F 2", "F",
            "X " + "00" * (line_size // 2),                 # longer than the line buffer: must not be truncated
        ]
    ] + [
        # Truncated but otherwise valid command must not run (catches a missing overflow check
        # deterministically; the case above also reads past the buffer if the check is gone).
        Case("F 0" + " " * line_size, bad, [], lacks=["RFOFF"]),
    ]


def check_tool(c, status_names):
    """tools/tsi_host.py must agree with the firmware it drives."""
    problems = []
    tool.self_check()  # CRC vs the wiki examples
    if tool.FW_MAX_BODY != c["MAX_BODY"]:
        problems.append(f"FW_MAX_BODY = {tool.FW_MAX_BODY} but TILELINK_MAX_BODY = {c['MAX_BODY']} "
                        "(dry-run would show the wrong packets)")
    if len(f"W 00000000 {'00' * tool.LINE_MAX_DATA}") > c["LINE_SIZE"]:
        problems.append(f"LINE_MAX_DATA = {tool.LINE_MAX_DATA} makes 'W' lines longer than TILELINK_LINE_SIZE")
    if len(f"X {'00' * tool.RAW_MAX}") > c["LINE_SIZE"] or tool.RAW_MAX > c["NFC_FIFO_SIZE"] - 5:
        problems.append(f"RAW_MAX = {tool.RAW_MAX} exceeds what the firmware accepts")
    if tool.TRF_STATUS != status_names:
        problems.append(f"TRF_STATUS {tool.TRF_STATUS} != tTrfStatus {status_names}")
    return problems


# ---- Runner -------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Host tests for the Tilelink firmware")
    parser.add_argument("-v", "--verbose", action="store_true", help="print each test's driver-call log")
    args = parser.parse_args()

    consts, status_names = generate()
    exe = build(find_cc())
    cases = make_cases(consts, status_names)

    stdin = "".join(f"{status_names.index(k.status)} {k.rx} {k.cmd}\n" for k in cases)
    result = subprocess.run([str(exe)], input=stdin, capture_output=True, text=True)
    if result.returncode:
        sys.exit(f"harness crashed (exit {result.returncode}):\n{result.stdout[-2000:]}\n{result.stderr}")
    blocks = [b for b in result.stdout.split("END\n") if b.strip()]
    if len(blocks) != len(cases):
        sys.exit(f"harness returned {len(blocks)} results for {len(cases)} tests:\n{result.stdout[-2000:]}")

    failures = 0
    for case, block in zip(cases, blocks):
        log = block.strip().splitlines()
        out = log[-1][4:]
        raws = [l[4:] for l in log if l.startswith("RAW ")]
        problems = []
        if out != case.out:
            problems.append(f"reply {out!r}, expected {case.out!r}")
        if case.raws is not None and raws != case.raws:
            problems.append(f"FIFO writes\n        got      {raws}\n        expected {case.raws}")
        problems += [f"missing '{h}'" for h in case.has if h not in log]
        problems += [f"unexpected '{h}...'" for h in case.lacks if any(l.startswith(h) for l in log)]

        label = case.cmd if len(case.cmd) <= 70 else case.cmd[:67] + "..."
        print(("PASS  " if not problems else "FAIL  ") + label)
        for p in problems:
            print("      " + p)
        if problems or args.verbose:
            print("      log: " + " / ".join(log[1:-1]))
        failures += bool(problems)

    tool_problems = check_tool(consts, status_names)
    print(("PASS  " if not tool_problems else "FAIL  ") + "tools/tsi_host.py matches the firmware")
    for p in tool_problems:
        print("      " + p)

    total = len(cases) + 1
    failed = failures + bool(tool_problems)
    print(f"\n{total - failed}/{total} passed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
